#!/usr/bin/env python3
"""Generate an auditable Minecraft Java/C++/Python protection plan.

The script materializes profile configuration and evidence targets.  It does
not invent or silently replace a missing commercial/native adapter.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path


LEVELS = {"light": 1, "medium": 2, "heavy": 3}


def has_tool(project: Path, name: str) -> bool:
    return bool(shutil.which(name) or list((project / ".reverse-tools").glob(f"**/{name}*")))


def keep_rules(project: Path) -> str:
    files = []
    for pattern in ("fabric.mod.json", "mods.toml", "*.mixins.json", "*.refmap.json", "*.accesswidener", "META-INF/services/*"):
        files.extend(str(p.relative_to(project)).replace("\\", "/") for p in project.glob(f"**/{pattern}") if p.is_file())
    lines = [
        "# Generated by polyglot-protector-orchestrator",
        "-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Record,PermittedSubclasses",
        "-keepclassmembers class ** { @org.spongepowered.asm.mixin.* *; }",
        "-keepclassmembers class ** { @net.fabricmc.api.* *; }",
        "-keep class net.fabricmc.loader.** { *; }",
        "-keep class net.minecraftforge.** { *; }",
        "-keep class cpw.mods.** { *; }",
        "-adaptclassstrings",
        "# Preserve discovered metadata/resource coupling:",
    ]
    lines.extend(f"# {item}" for item in sorted(set(files)))
    return "\n".join(lines) + "\n"


def profile(level: str, languages: list[str], project: Path) -> dict:
    depth = LEVELS[level]
    steps = []

    def add(step_id: str, language: str, tool: str, action: str, evidence: str, optional: bool = False):
        present = has_tool(project, tool) if tool not in {"gradle", "javac", "cmake", "clang++", "python"} else bool(shutil.which(tool) or (project / f"{tool}w.bat").is_file())
        steps.append({"id": step_id, "language": language, "tool": tool, "action": action, "evidence_target": evidence, "optional": optional, "status": "ready" if present else "blocked_missing_tool"})

    if "java" in languages:
        add("java-archive", "java", "jar", "inventory JAR/classes/resources and record hashes", "reports/java-archive.json")
        add("java-keep", "java", "gradle", "apply generated Minecraft keep rules and mapping output", "reports/minecraft-metadata.json")
        if depth >= 2:
            add("java-string-constant", "java", "recaf", "apply selected string/constant transform to an allowlist", "reports/java-transform.json", True)
            add("java-flow", "java", "java-deobfuscator", "apply detector-matched control-flow/indy pass", "reports/java-flow.json", True)
        if depth >= 3:
            add("java-native", "java", "native-obfuscator", "transpile selected methods to native with an explicit allowlist", "reports/java-native-map.csv", True)
            add("java-vm", "java", "phantomshield", "apply selected VM/verification adapter if installed", "reports/java-vm.json", True)
    if "cpp" in languages:
        add("cpp-symbols", "cpp", "cmake", "configure hidden visibility, section GC, LTO, and release symbols", "reports/cpp-build.json")
        if depth >= 2:
            add("cpp-hardening", "cpp", "clang++", "compile selected native sources with hardening flags", "reports/cpp-hardening.json", True)
        if depth >= 3:
            add("cpp-llvm", "cpp", "clang++", "apply an installed LLVM obfuscation pass to selected targets", "reports/cpp-llvm.json", True)
    if "python" in languages:
        add("python-bytecode", "python", "python", "compile deterministic bytecode/package and remove source metadata", "reports/python-package.json")
        if depth >= 2:
            add("python-pyarmor", "python", "pyarmor", "protect selected Python modules", "reports/python-pyarmor.json", True)
        if depth >= 3:
            add("python-native", "python", "nuitka", "compile selected modules and record extension ABI", "reports/python-native.json", True)
    return {"schema": "minecraft-protection-plan/v1", "level": level, "languages": languages, "project": str(project), "steps": steps, "metadata_keep_rules": keep_rules(project), "rollback": {"original_immutable": True, "stages_directory": "stages", "logs_directory": "logs"}}


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    plan = sub.add_parser("plan")
    plan.add_argument("--project", type=Path, required=True)
    plan.add_argument("--level", choices=sorted(LEVELS), required=True)
    plan.add_argument("--languages", default="java,cpp,python")
    plan.add_argument("--out", type=Path, required=True)
    apply = sub.add_parser("apply")
    apply.add_argument("--plan", type=Path, required=True)
    apply.add_argument("--out-dir", type=Path, default=None)
    args = parser.parse_args()
    if args.command == "plan":
        project = args.project.resolve()
        data = profile(args.level, [x.strip() for x in args.languages.split(",") if x.strip()], project)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps({"steps": len(data["steps"]), "blocked": sum(s["status"] != "ready" for s in data["steps"])}, ensure_ascii=False))
        return 0
    plan_data = json.loads(args.plan.read_text(encoding="utf-8"))
    out_dir = (args.out_dir or args.plan.parent / "materialized").resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "minecraft-keep.pro").write_text(plan_data.get("metadata_keep_rules", ""), encoding="utf-8")
    (out_dir / "cmake-hardening.cmake").write_text("set(CMAKE_CXX_VISIBILITY_PRESET hidden)\nset(CMAKE_VISIBILITY_INLINES_HIDDEN YES)\nset(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)\n", encoding="utf-8")
    (out_dir / "python-profile.toml").write_text("[package]\nsource_metadata = false\ndeterministic = true\n", encoding="utf-8")
    manifest = {"plan_sha256": hashlib.sha256(args.plan.read_bytes()).hexdigest(), "plan": str(args.plan.resolve()), "steps": plan_data.get("steps", []), "status": "materialized"}
    (out_dir / "protection-manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"out_dir": str(out_dir), "status": "materialized"}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
